### ISSUE TITLE
AttributeError: 'DataBlock' object has no attribute 'instructions'

### ISSUE THREAD

**Issue by zeroSteiner** [zeroSteiner/crimson-forge#2]
```
Traceback (most recent call last):
  File "./crimson-forge", line 36, in <module>
    cli.main()
  File "/home/silburfuchs/tools/crimson-forge/crimson_forge/cli.py", line 280, in main
    tainted_self_refs = crimson_forge.analysis.symexec_tainted_self_reference_identification(exec_seg)
  File "/home/silburfuchs/tools/crimson-forge/crimson_forge/analysis.py", line 322, in symexec_tainted_self_reference_identification
    return not _simulate_state_recursively(state, collections.deque())
  File "/home/silburfuchs/tools/crimson-forge/crimson_forge/analysis.py", line 319, in _simulate_state_recursively
    result = result and _simulate_state_recursively(new_state, history)
  File "/home/silburfuchs/tools/crimson-forge/crimson_forge/analysis.py", line 319, in _simulate_state_recursively
    result = result and _simulate_state_recursively(new_state, history)
  File "/home/silburfuchs/tools/crimson-forge/crimson_forge/analysis.py", line 308, in _simulate_state_recursively
    simgr.step(num_inst=len(blk.instructions))
AttributeError: 'DataBlock' object has no attribute 'instructions'
```

**Comment by l4ckyguy** [comment]
Traceback (most recent call last):
  File "/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==11.9.0', 'console_scripts', 'pipenv')()
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pipenv/cli.py", line 602, in run
    core.do_run(command=command, args=args, three=three, python=python)
  File "/usr/lib/python3/dist-packages/pipenv/core.py", line 2200, in do_run
    command = ' '.join(project.scripts[command])
  File "/usr/lib/python3/dist-packages/pipenv/project.py", line 374, in scripts
    scripts[k] = shlex.split(v, posix=True)
  File "/usr/lib/python3.8/shlex.py", line 311, in split
    return list(lex)
  File "/usr/lib/python3.8/shlex.py", line 300, in __next__
    token = self.get_token()
  File "/usr/lib/python3.8/shlex.py", line 109, in get_token
    raw = self.read_token()
  File "/usr/lib/python3.8/shlex.py", line 140, in read_token
    nextchar = self.instream.read(1)
AttributeError: 'list' object has no attribute 'read'

**Comment by l4ckyguy** [comment]
im very sorry =)

**Comment by zeroSteiner** [comment]
@l4ckyguy I'm pretty confident that issue is unrelated to Crimson Forge and is actually with your pipenv installation. I've seen a similar stack trace reported on other [projects](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=945139). I'd recommend reinstalling / upgrading your pipenv install and trying again. If the problem persists, please open a new ticket since it's unrelated to this issue.
