### ISSUE TITLE
Pipenv fails to install several dependencies

### ISSUE THREAD

**Issue by Silburfuchs** [zeroSteiner/crimson-forge#4]
When installing crimson-forge via pipenv a couple of dependencies fail to install. See below for the full commands and terminal output.
OS: Fedora 31 (virtual machine)
Branch: master
Pipenv version: version 2018.11.26

```sudo pipenv install
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
✔ Success! 
Locking [packages] dependencies…
✔ Success! 
Updated Pipfile.lock (3cd13f)!
Installing dependencies from Pipfile.lock (3cd13f)…
An error occurred while installing angr==8.19.4.5 --hash=sha256:386efa0b110883059e5bf195fea25223a859d42075e60582ed95bb64ad7086fa --hash=sha256:3b24763494f85d1af600eb39fae6e42f0fa4583dfd8f17c069c62c6bda5e9a56 --hash=sha256:87f271fe749395cb772dda135e5e458db8d9cc49d724597e0e0f7c70d2a96380 --hash=sha256:b3bbcbc0fc140146f076c087d4efc8681ac579e46251d5ff8b086249a3fddf1c --hash=sha256:d8c94e27dc1a017e5fe39034b8f6af53527fbf44509a81b09dd93f79af56a2f7! Will try again.
An error occurred while installing psutil==5.6.7 --hash=sha256:094f899ac3ef72422b7e00411b4ed174e3c5a2e04c267db6643937ddba67a05b --hash=sha256:10b7f75cc8bd676cfc6fa40cd7d5c25b3f45a0e06d43becd7c2d2871cbb5e806 --hash=sha256:1b1575240ca9a90b437e5a40db662acd87bbf181f6aa02f0204978737b913c6b --hash=sha256:21231ef1c1a89728e29b98a885b8e0a8e00d09018f6da5cdc1f43f988471a995 --hash=sha256:28f771129bfee9fc6b63d83a15d857663bbdcae3828e1cb926e91320a9b5b5cd --hash=sha256:70387772f84fa5c3bb6a106915a2445e20ac8f9821c5914d7cbde148f4d7ff73 --hash=sha256:b560f5cd86cf8df7bcd258a851ca1ad98f0d5b8b98748e877a0aec4e9032b465 --hash=sha256:b74b43fecce384a57094a83d2778cdfc2e2d9a6afaadd1ebecb2e75e0d34e10d --hash=sha256:e85f727ffb21539849e6012f47b12f6dd4c44965e56591d8dec6e8bc9ab96f4a --hash=sha256:fd2e09bb593ad9bdd7429e779699d2d47c1268cbde4dda95fcd1bd17544a0217 --hash=sha256:ffad8eb2ac614518bbe3c0b8eb9dffdb3a8d2e3a7d5da51c5b974fb723a5c5aa! Will try again.
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 45/45 — 00:00:30
An error occurred while installing unicorn==1.0.1 --hash=sha256:2a0a43ebf73da8e79e91e89b4e72ab2413a410167db4dff25008721ec117cda1 --hash=sha256:3a8ad7a7f4be7583e77ca2f7f921a26081eb4987a37afbd8c91850eb6a8a673c --hash=sha256:66bada80960b2d7da45408acd10d2ea8fdf2c51781543d4e9401d10480b6a574 --hash=sha256:6f25eef8119620d54cf17472be7fbd3566143a72ff5ff5a6e3639171e026ab28 --hash=sha256:7e827ac975f5f1ad0022009df22c6af7db7e5229e7878835ee059d4dc16217c4! Will try again.
An error occurred while installing z3-solver==4.5.1.0.post2 --hash=sha256:474a22a1c6b26a89fc0fe563a9e0738bf1ff6b6f645f3b1d7a4beda18b3f44bc --hash=sha256:6b10b317f056890a341304071fb3ab220f0adb2c87439a04eba9e69028a7e3ff --hash=sha256:c185d05d236c6c9756e914756c73f797cb618d81b42e694166639cce5bcfdb1f --hash=sha256:c802dbe5368743dd30dd2a684c15b83b17c3c95df54b66f97611a5988ae0f696 --hash=sha256:cf57c53f1e366f3f6bc806fd83ad288b9c82ee8d2bbdfdc64d53767aaf500209 --hash=sha256:e41001b7f43ecb9eb9bedf6762bd0e002561590487cc78c0b48f608a85ce02ac --hash=sha256:f472f1d0d04856cfaf15d0ebab5ff39b2b1bc09b2f4d2119c0ba0540121b5265! Will try again.
Installing initially failed dependencies…
  ☤  ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 4/4 — 00:00:15
[pipenv.exceptions.InstallError]: ['Collecting angr==8.19.4.5', '  Using cached angr-8.19.4.5.tar.gz (834 kB)']
[pipenv.exceptions.InstallError]: ['ERROR: Command errored out with exit status 1:', '     command: /root/.local/share/virtualenvs/crimson-forge-DIUU_OG7/bin/python3 -c \'import sys, setuptools, tokenize; sys.argv[0] = \'"\'"\'/tmp/pip-install-qya89nsb/angr/setup.py\'"\'"\'; __file__=\'"\'"\'/tmp/pip-install-qya89nsb/angr/setup.py\'"\'"\';f=getattr(tokenize, \'"\'"\'open\'"\'"\', open)(__file__);code=f.read().replace(\'"\'"\'\\r\\n\'"\'"\', \'"\'"\'\\n\'"\'"\');f.close();exec(compile(code, __file__, \'"\'"\'exec\'"\'"\'))\' egg_info --egg-base /tmp/pip-install-qya89nsb/angr/pip-egg-info', '         cwd: /tmp/pip-install-qya89nsb/angr/', '    Complete output (49 lines):', '      ERROR: Command errored out with exit status 1:', '       command: /root/.local/share/virtualenvs/crimson-forge-DIUU_OG7/bin/python3 -u -c \'import sys, setuptools, tokenize; sys.argv[0] = \'"\'"\'/tmp/pip-wheel-ieobx12r/unicorn/setup.py\'"\'"\'; __file__=\'"\'"\'/tmp/pip-wheel-ieobx12r/unicorn/setup.py\'"\'"\';f=getattr(tokenize, \'"\'"\'open\'"\'"\', open)(__file__);code=f.read().replace(\'"\'"\'\\r\\n\'"\'"\', \'"\'"\'\\n\'"\'"\');f.close();exec(compile(code, __file__, \'"\'"\'exec\'"\'"\'))\' bdist_wheel -d /tmp/pip-wheel-0kjxuj80', '           cwd: /tmp/pip-wheel-ieobx12r/unicorn/', '      Complete output (12 lines):', '      running bdist_wheel', '      running build', '      Building C extensions', '      cd qemu && \\', '      ./configure --cc="cc" --extra-cflags="-DUNICORN_HAS_X86 -DUNICORN_HAS_ARM -DUNICORN_HAS_ARMEB -DUNICORN_HAS_M68K -DUNICORN_HAS_ARM64 -DUNICORN_HAS_MIPS -DUNICORN_HAS_MIPSEL -DUNICORN_HAS_MIPS64 -DUNICORN_HAS_MIPS64EL -DUNICORN_HAS_SPARC -fPIC -fvisibility=hidden" --target-list="x86_64-softmmu, arm-softmmu, armeb-softmmu, m68k-softmmu, aarch64-softmmu, mips-softmmu, mipsel-softmmu, mips64-softmmu, mips64el-softmmu, sparc-softmmu,sparc64-softmmu,"', '    ', "      ERROR: Cannot use 'python', Python 2.4 or later is required.", '             Note that Python 3 or later is not yet supported.', '             Use --python=/path/to/python to specify a supported Python.', '    ', '      make: *** [Makefile:214: qemu/config-host.h-timestamp] Error 1', "      error: [Errno 2] No such file or directory: 'libunicorn.so'", '      ----------------------------------------', '      ERROR: Failed building wheel for unicorn', '    ERROR: Failed to build one or more wheels', '    Traceback (most recent call last):', '      File "/root/.local/share/virtualenvs/crimson-forge-DIUU_OG7/lib/python3.7/site-packages/setuptools/installer.py", line 128, in fetch_build_egg', '        subprocess.check_call(cmd)', '      File "/usr/lib64/python3.7/subprocess.py", line 363, in check_call', '        raise CalledProcessError(retcode, cmd)', "    subprocess.CalledProcessError: Command '['/root/.local/share/virtualenvs/crimson-forge-DIUU_OG7/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpn_kayssz', '--quiet', 'unicorn']' returned non-zero exit status 1.", '    ', '    During handling of the above exception, another exception occurred:', '    ', '    Traceback (most recent call last):', '      File "<string>", line 1, in <module>', '      File "/tmp/pip-install-qya89nsb/angr/setup.py", line 149, in <module>', "        'angr': ['lib/*']", '      File "/root/.local/share/virtualenvs/crimson-forge-DIUU_OG7/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup', '        _install_setup_requires(attrs)', '      File "/root/.local/share/virtualenvs/crimson-forge-DIUU_OG7/lib/python3.7/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires', '        dist.fetch_build_eggs(dist.setup_requires)', '      File "/root/.local/share/virtualenvs/crimson-forge-DIUU_OG7/lib/python3.7/site-packages/setuptools/dist.py", line 721, in fetch_build_eggs', '        replace_conflicting=True,', '      File "/root/.local/share/virtualenvs/crimson-forge-DIUU_OG7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 783, in resolve', '        replace_conflicting=replace_conflicting', '      File "/root/.local/share/virtualenvs/crimson-forge-DIUU_OG7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1066, in best_match', '        return self.obtain(req, installer)', '      File "/root/.local/share/virtualenvs/crimson-forge-DIUU_OG7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1078, in obtain', '        return installer(requirement)', '      File "/root/.local/share/virtualenvs/crimson-forge-DIUU_OG7/lib/python3.7/site-packages/setuptools/dist.py", line 777, in fetch_build_egg', '        return fetch_build_egg(self, req)', '      File "/root/.local/share/virtualenvs/crimson-forge-DIUU_OG7/lib/python3.7/site-packages/setuptools/installer.py", line 130, in fetch_build_egg', '        raise DistutilsError(str(e))', "    distutils.errors.DistutilsError: Command '['/root/.local/share/virtualenvs/crimson-forge-DIUU_OG7/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpn_kayssz', '--quiet', 'unicorn']' returned non-zero exit status 1.", '    ----------------------------------------', 'ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.']
ERROR: ERROR: Package installation failed...
```

**Comment by zeroSteiner** [comment]
I *know* I was able to reproduce this when you originally opened this issue. Then I kinda forgot about it until today when I needed to install Crimson Forge and thought I'd look into it again and the issue seems gone.

@Silburfuchs can you verify that you're still getting this issue? Please remove your existing, broken virtual environment by running `pipenv --rm` first and then running `pipenv install` again. I'm wondering if there was an upstream bug that's since been fixed.

**Comment by Silburfuchs** [comment]
I removed the environment and attempted to install again. It looks like it got further this time, but still errored out. Failed to grab 2 dependencies.

```ghost@rogue  /opt/crimson-forge  master  pipenv --rm
Removing virtualenv (/home/ghost/.local/share/virtualenvs/crimson-forge-DIUU_OG7)…
 ghost@rogue  /opt/crimson-forge  master  pipenv install
Creating a virtualenv for this project…
Pipfile: /opt/crimson-forge/Pipfile
Using /usr/bin/python3 (3.7.6) to create virtualenv…
⠇ Creating virtual environment...Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/ghost/.local/share/virtualenvs/crimson-forge-DIUU_OG7/bin/python3
Also creating executable in /home/ghost/.local/share/virtualenvs/crimson-forge-DIUU_OG7/bin/python
Installing setuptools, pip, wheel...
done.

✔ Successfully created virtual environment! 
Virtualenv location: /home/ghost/.local/share/virtualenvs/crimson-forge-DIUU_OG7
Installing dependencies from Pipfile.lock (3cd13f)…
An error occurred while installing psutil==5.6.7 --hash=sha256:094f899ac3ef72422b7e00411b4ed174e3c5a2e04c267db6643937ddba67a05b --hash=sha256:10b7f75cc8bd676cfc6fa40cd7d5c25b3f45a0e06d43becd7c2d2871cbb5e806 --hash=sha256:1b1575240ca9a90b437e5a40db662acd87bbf181f6aa02f0204978737b913c6b --hash=sha256:21231ef1c1a89728e29b98a885b8e0a8e00d09018f6da5cdc1f43f988471a995 --hash=sha256:28f771129bfee9fc6b63d83a15d857663bbdcae3828e1cb926e91320a9b5b5cd --hash=sha256:70387772f84fa5c3bb6a106915a2445e20ac8f9821c5914d7cbde148f4d7ff73 --hash=sha256:b560f5cd86cf8df7bcd258a851ca1ad98f0d5b8b98748e877a0aec4e9032b465 --hash=sha256:b74b43fecce384a57094a83d2778cdfc2e2d9a6afaadd1ebecb2e75e0d34e10d --hash=sha256:e85f727ffb21539849e6012f47b12f6dd4c44965e56591d8dec6e8bc9ab96f4a --hash=sha256:fd2e09bb593ad9bdd7429e779699d2d47c1268cbde4dda95fcd1bd17544a0217 --hash=sha256:ffad8eb2ac614518bbe3c0b8eb9dffdb3a8d2e3a7d5da51c5b974fb723a5c5aa! Will try again.
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 45/45 — 00:01:36
An error occurred while installing pyvex==8.19.4.5 --hash=sha256:39ede1025194ffdf29de7e839d0c216756c4d4b57c3e61239783035e4fce892d --hash=sha256:67292ba8b2f4e8da31adb3728d29c19ab23730c8cd40c0cafce3d5267426c2b0 --hash=sha256:a40d8f1041e428b7dbce969b1a4d3496d079282daeb3b19c95b01e8156a76934 --hash=sha256:c9675e1c6d799aa1901122ed84809031ba9c9db6c9f7279f860ea39df86a1bf8 --hash=sha256:ee5f3529f232035e0a81176c598b241b5425be29fd6b6bb262feeeb27cad41de! Will try again.
Installing initially failed dependencies…
  ☤  ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 2/2 — 00:00:06
[pipenv.exceptions.InstallError]: ['Collecting psutil==5.6.7', '  Using cached psutil-5.6.7.tar.gz (448 kB)', 'Building wheels for collected packages: psutil', '  Building wheel for psutil (setup.py): started', "  Building wheel for psutil (setup.py): finished with status 'error'", '  Running setup.py clean for psutil', 'Failed to build psutil', 'Installing collected packages: psutil', '    Running setup.py install for psutil: started', "    Running setup.py install for psutil: finished with status 'error'"]
[pipenv.exceptions.InstallError]: ['ERROR: Command errored out with exit status 1:', '   command: /home/ghost/.local/share/virtualenvs/crimson-forge-DIUU_OG7/bin/python3 -u -c \'import sys, setuptools, tokenize; sys.argv[0] = \'"\'"\'/tmp/pip-install-83lmgquv/psutil/setup.py\'"\'"\'; __file__=\'"\'"\'/tmp/pip-install-83lmgquv/psutil/setup.py\'"\'"\';f=getattr(tokenize, \'"\'"\'open\'"\'"\', open)(__file__);code=f.read().replace(\'"\'"\'\\r\\n\'"\'"\', \'"\'"\'\\n\'"\'"\');f.close();exec(compile(code, __file__, \'"\'"\'exec\'"\'"\'))\' bdist_wheel -d /tmp/pip-wheel-6znmto2l', '       cwd: /tmp/pip-install-83lmgquv/psutil/', '  Complete output (46 lines):', '  running bdist_wheel', '  running build', '  running build_py', '  creating build', '  creating build/lib.linux-x86_64-3.7', '  creating build/lib.linux-x86_64-3.7/psutil', '  copying psutil/_pswindows.py -> build/lib.linux-x86_64-3.7/psutil', '  copying psutil/_pssunos.py -> build/lib.linux-x86_64-3.7/psutil', '  copying psutil/_psposix.py -> build/lib.linux-x86_64-3.7/psutil', '  copying psutil/_psosx.py -> build/lib.linux-x86_64-3.7/psutil', '  copying psutil/_pslinux.py -> build/lib.linux-x86_64-3.7/psutil', '  copying psutil/_psbsd.py -> build/lib.linux-x86_64-3.7/psutil', '  copying psutil/_psaix.py -> build/lib.linux-x86_64-3.7/psutil', '  copying psutil/_compat.py -> build/lib.linux-x86_64-3.7/psutil', '  copying psutil/_common.py -> build/lib.linux-x86_64-3.7/psutil', '  copying psutil/__init__.py -> build/lib.linux-x86_64-3.7/psutil', '  creating build/lib.linux-x86_64-3.7/psutil/tests', '  copying psutil/tests/test_windows.py -> build/lib.linux-x86_64-3.7/psutil/tests', '  copying psutil/tests/test_unicode.py -> build/lib.linux-x86_64-3.7/psutil/tests', '  copying psutil/tests/test_system.py -> build/lib.linux-x86_64-3.7/psutil/tests', '  copying psutil/tests/test_sunos.py -> build/lib.linux-x86_64-3.7/psutil/tests', '  copying psutil/tests/test_process.py -> build/lib.linux-x86_64-3.7/psutil/tests', '  copying psutil/tests/test_posix.py -> build/lib.linux-x86_64-3.7/psutil/tests', '  copying psutil/tests/test_osx.py -> build/lib.linux-x86_64-3.7/psutil/tests', '  copying psutil/tests/test_misc.py -> build/lib.linux-x86_64-3.7/psutil/tests', '  copying psutil/tests/test_memory_leaks.py -> build/lib.linux-x86_64-3.7/psutil/tests', '  copying psutil/tests/test_linux.py -> build/lib.linux-x86_64-3.7/psutil/tests', '  copying psutil/tests/test_contracts.py -> build/lib.linux-x86_64-3.7/psutil/tests', '  copying psutil/tests/test_connections.py -> build/lib.linux-x86_64-3.7/psutil/tests', '  copying psutil/tests/test_bsd.py -> build/lib.linux-x86_64-3.7/psutil/tests', '  copying psutil/tests/test_aix.py -> build/lib.linux-x86_64-3.7/psutil/tests', '  copying psutil/tests/runner.py -> build/lib.linux-x86_64-3.7/psutil/tests', '  copying psutil/tests/__main__.py -> build/lib.linux-x86_64-3.7/psutil/tests', '  copying psutil/tests/__init__.py -> build/lib.linux-x86_64-3.7/psutil/tests', '  warning: build_py: byte-compiling is disabled, skipping.', '  ', '  running build_ext', "  building 'psutil._psutil_linux' extension", '  creating build/temp.linux-x86_64-3.7', '  creating build/temp.linux-x86_64-3.7/psutil', '  gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_VERSION=567 -DPSUTIL_LINUX=1 -I/usr/include/python3.7m -c psutil/_psutil_common.c -o build/temp.linux-x86_64-3.7/psutil/_psutil_common.o', '  psutil/_psutil_common.c:9:10: fatal error: Python.h: No such file or directory', '      9 | #include <Python.h>', '        |          ^~~~~~~~~~', '  compilation terminated.', "  error: command 'gcc' failed with exit status 1", '  ----------------------------------------', '  ERROR: Failed building wheel for psutil', '    ERROR: Command errored out with exit status 1:', '     command: /home/ghost/.local/share/virtualenvs/crimson-forge-DIUU_OG7/bin/python3 -u -c \'import sys, setuptools, tokenize; sys.argv[0] = \'"\'"\'/tmp/pip-install-83lmgquv/psutil/setup.py\'"\'"\'; __file__=\'"\'"\'/tmp/pip-install-83lmgquv/psutil/setup.py\'"\'"\';f=getattr(tokenize, \'"\'"\'open\'"\'"\', open)(__file__);code=f.read().replace(\'"\'"\'\\r\\n\'"\'"\', \'"\'"\'\\n\'"\'"\');f.close();exec(compile(code, __file__, \'"\'"\'exec\'"\'"\'))\' install --record /tmp/pip-record-8l2i485s/install-record.txt --single-version-externally-managed --compile --install-headers /home/ghost/.local/share/virtualenvs/crimson-forge-DIUU_OG7/include/site/python3.7/psutil', '         cwd: /tmp/pip-install-83lmgquv/psutil/', '    Complete output (46 lines):', '    running install', '    running build', '    running build_py', '    creating build', '    creating build/lib.linux-x86_64-3.7', '    creating build/lib.linux-x86_64-3.7/psutil', '    copying psutil/_pswindows.py -> build/lib.linux-x86_64-3.7/psutil', '    copying psutil/_pssunos.py -> build/lib.linux-x86_64-3.7/psutil', '    copying psutil/_psposix.py -> build/lib.linux-x86_64-3.7/psutil', '    copying psutil/_psosx.py -> build/lib.linux-x86_64-3.7/psutil', '    copying psutil/_pslinux.py -> build/lib.linux-x86_64-3.7/psutil', '    copying psutil/_psbsd.py -> build/lib.linux-x86_64-3.7/psutil', '    copying psutil/_psaix.py -> build/lib.linux-x86_64-3.7/psutil', '    copying psutil/_compat.py -> build/lib.linux-x86_64-3.7/psutil', '    copying psutil/_common.py -> build/lib.linux-x86_64-3.7/psutil', '    copying psutil/__init__.py -> build/lib.linux-x86_64-3.7/psutil', '    creating build/lib.linux-x86_64-3.7/psutil/tests', '    copying psutil/tests/test_windows.py -> build/lib.linux-x86_64-3.7/psutil/tests', '    copying psutil/tests/test_unicode.py -> build/lib.linux-x86_64-3.7/psutil/tests', '    copying psutil/tests/test_system.py -> build/lib.linux-x86_64-3.7/psutil/tests', '    copying psutil/tests/test_sunos.py -> build/lib.linux-x86_64-3.7/psutil/tests', '    copying psutil/tests/test_process.py -> build/lib.linux-x86_64-3.7/psutil/tests', '    copying psutil/tests/test_posix.py -> build/lib.linux-x86_64-3.7/psutil/tests', '    copying psutil/tests/test_osx.py -> build/lib.linux-x86_64-3.7/psutil/tests', '    copying psutil/tests/test_misc.py -> build/lib.linux-x86_64-3.7/psutil/tests', '    copying psutil/tests/test_memory_leaks.py -> build/lib.linux-x86_64-3.7/psutil/tests', '    copying psutil/tests/test_linux.py -> build/lib.linux-x86_64-3.7/psutil/tests', '    copying psutil/tests/test_contracts.py -> build/lib.linux-x86_64-3.7/psutil/tests', '    copying psutil/tests/test_connections.py -> build/lib.linux-x86_64-3.7/psutil/tests', '    copying psutil/tests/test_bsd.py -> build/lib.linux-x86_64-3.7/psutil/tests', '    copying psutil/tests/test_aix.py -> build/lib.linux-x86_64-3.7/psutil/tests', '    copying psutil/tests/runner.py -> build/lib.linux-x86_64-3.7/psutil/tests', '    copying psutil/tests/__main__.py -> build/lib.linux-x86_64-3.7/psutil/tests', '    copying psutil/tests/__init__.py -> build/lib.linux-x86_64-3.7/psutil/tests', '    warning: build_py: byte-compiling is disabled, skipping.', '    ', '    running build_ext', "    building 'psutil._psutil_linux' extension", '    creating build/temp.linux-x86_64-3.7', '    creating build/temp.linux-x86_64-3.7/psutil', '    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_VERSION=567 -DPSUTIL_LINUX=1 -I/usr/include/python3.7m -c psutil/_psutil_common.c -o build/temp.linux-x86_64-3.7/psutil/_psutil_common.o', '    psutil/_psutil_common.c:9:10: fatal error: Python.h: No such file or directory', '        9 | #include <Python.h>', '          |          ^~~~~~~~~~', '    compilation terminated.', "    error: command 'gcc' failed with exit status 1", '    ----------------------------------------', 'ERROR: Command errored out with exit status 1: /home/ghost/.local/share/virtualenvs/crimson-forge-DIUU_OG7/bin/python3 -u -c \'import sys, setuptools, tokenize; sys.argv[0] = \'"\'"\'/tmp/pip-install-83lmgquv/psutil/setup.py\'"\'"\'; __file__=\'"\'"\'/tmp/pip-install-83lmgquv/psutil/setup.py\'"\'"\';f=getattr(tokenize, \'"\'"\'open\'"\'"\', open)(__file__);code=f.read().replace(\'"\'"\'\\r\\n\'"\'"\', \'"\'"\'\\n\'"\'"\');f.close();exec(compile(code, __file__, \'"\'"\'exec\'"\'"\'))\' install --record /tmp/pip-record-8l2i485s/install-record.txt --single-version-externally-managed --compile --install-headers /home/ghost/.local/share/virtualenvs/crimson-forge-DIUU_OG7/include/site/python3.7/psutil Check the logs for full command output.']
ERROR: ERROR: Package installation failed...```

**Comment by zeroSteiner** [comment]
Okay, now it looks like you're missing the `python3-devel` package which makes sense since you need to compile some native extensions.

Try running: `sudo dnf install python3-devel` and then installing again.

**Comment by Silburfuchs** [comment]
That did it, everything seems to be working now. Thanks for the help!

**Comment by zeroSteiner** [comment]
Awesome thanks for checking. I'll see about documenting that as a dependency.
